In [ ]:
 # The function is defined as:
    # f(00) = f(11) = 00
    # f(01) = f(10) = 11

∣x,y⟩→∣x,y⊕f(x)⟩ 
∣00,00⟩→∣00,00⟩
∣00,01⟩→∣00,01⟩
∣00,10⟩→∣00,10⟩
∣00,11⟩→∣00,11⟩,
∣01,00⟩→∣01,11⟩
∣01,01⟩→∣01,10⟩
∣01,10⟩→∣01,01⟩
∣01,11⟩→∣01,00⟩
∣10,00⟩→∣10,11⟩
∣10,01⟩→∣10,10⟩
∣10,10⟩→∣10,01⟩
∣10,11⟩→∣10,00⟩
∣11,00⟩→∣11,00⟩
∣11,01⟩→∣11,01⟩
∣11,10⟩→∣11,10⟩
∣11,11⟩→∣11,11⟩

In [2]:
import numpy as np

# Directly initialize the 16x16 transformation matrix
T = np.array([
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
])

# Print the transformation matrix
print(T)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [ ]:
import cirq
import numpy as np
from collections import Counter

# Define the 8x8 unitary matrix for the oracle function
oracle_matrix = np.array([
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
])



# Create the oracle gate from the unitary matrix
oracle_gate = cirq.MatrixGate(oracle_matrix)

# Define the quantum circuit
def simon_circuit(oracle_gate):
    # Define four qubits
    qubits = cirq.LineQubit.range(4)                #2 input line + 2 output line
    
    # Create a quantum circuit
    circuit = cirq.Circuit()

    # Apply Hadamard gate to the first two qubits
    circuit.append([cirq.H(qubits[i]) for i in range(2)])

    # Apply the oracle gate
    circuit.append(oracle_gate(*qubits))

    # Apply Hadamard gate to the first two qubits
    circuit.append([cirq.H(qubits[i]) for i in range(2)])

    # Measure the first two qubits
    circuit.append([cirq.measure(qubits[i], key=f'result_{i}') for i in range(2)])

    return circuit

# Create the quantum circuit with the oracle gate
circuit = simon_circuit(oracle_gate)
# Simulate the circuit 100 times
simulator = cirq.Simulator()
result = simulator.run(circuit, repetitions=100)

# Collect the measurement results
measurements = result.measurements
counts = Counter(tuple(measurements[f'result_{i}'][j][0] for i in range(2)) for j in range(100))

# Print the measurement results
print("Measurement results (bitstring: frequency):")
for outcome, frequency in counts.items():
    print(f"{outcome}: {frequency}")

# Print the circuit
print("\nCircuit:")
print(circuit)

Measurement results (bitstring: frequency):
(1, 1): 48
(0, 0): 52

Circuit:
          ┌                               ┐
          │1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0│
          │0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0│
          │0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0│
0: ───H───│0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0│───H───M('result_0')───
          │0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0│
          │0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0│
          │0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0│
          │0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0│
          │0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0│
          │0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0│
          │0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0│
          │0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1│
          └                               ┘
          │
1: ───H───#2──────────────────────────────────H───M('result_1')───
          │
2: ───────#3──────

In [ ]:
Given that ( c ) is a two-bit binary number, we need to find ( c ) such that its inner product
with ( 00 ) and ( 11 ) is zero. 

Let's denote ( c ) as ( c = c1c0 ). 

The inner product of two binary numbers ( a ) and ( b ) is defined as: 

[ a . b = a0 . b0 + a1 . b1 ] 


Given the binary numbers: 

1. ( 00 ) 

2. ( 11 ) 

  
We need ( c ) such that: 


[ c . 00 = 0 ] 

[ c . 11 = 0 ] 

  

Let's calculate the inner products: 


1. ( c . 00 = c1 . 0 + c0 . 0 = 0 ) 

   This condition is trivially satisfied for any ( c ). 

  

2. ( c . 11 = c1 . 1 + c0 . 1 = c1 + c0 ) 

Therefore, ( c ) must satisfy the condition ( c1 = c0 ). The possible values for ( c ) are: 

  
( c = 00 ) 

( c = 11 ) 


Thus, the possible values of ( c ) that satisfy the given conditions are ( 00 ) and ( 11 ). 

In [4]:
# Find period for this

# f(00) = f(10) = 00
# f(01) = f(11) = 11

# 10 period

import cirq
import numpy as np
from collections import Counter

# Define the 4 function outputs manually (in decimal: 0,1,2,3 = 00,01,10,11)
f_00 = 0  # f(00) = 00
f_01 = 3  # f(01) = 11  
f_10 = 0  # f(10) = 00
f_11 = 3  # f(11) = 11

# Create function dictionary
f = {0: f_00, 1: f_01, 2: f_10, 3: f_11}

# Generate 16x16 matrix for |x,y⟩ → |x, y⊕f(x)⟩
T = np.zeros((16, 16), dtype=int)

for i in range(16):
    x = (i >> 2) & 0b11  # Extract first 2 bits (x)
    y = i & 0b11         # Extract last 2 bits (y)
    
    new_y = y ^ f[x]     # Compute y ⊕ f(x)
    j = (x << 2) | new_y # Combine x and new_y
    
    T[i, j] = 1

print("Matrix T:")
print(T)



Matrix T:
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]]


In [ ]:
import cirq
import numpy as np
from collections import Counter

# Define the 8x8 unitary matrix for the oracle function
oracle_matrix = np.array([
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
])

# Create the oracle gate from the unitary matrix
oracle_gate = cirq.MatrixGate(oracle_matrix)

# Define the quantum circuit
def simon_circuit(oracle_gate):
    # Define four qubits
    qubits = cirq.LineQubit.range(4)                #2 input line + 2 output line
    
    # Create a quantum circuit
    circuit = cirq.Circuit()

    # Apply Hadamard gate to the first two qubits
    circuit.append([cirq.H(qubits[i]) for i in range(2)])

    # Apply the oracle gate
    circuit.append(oracle_gate(*qubits))

    # Apply Hadamard gate to the first two qubits
    circuit.append([cirq.H(qubits[i]) for i in range(2)])

    # Measure the first two qubits
    circuit.append([cirq.measure(qubits[i], key=f'result_{i}') for i in range(2)])

    return circuit

# Create the quantum circuit with the oracle gate
circuit = simon_circuit(oracle_gate)
# Simulate the circuit 100 times
simulator = cirq.Simulator()
result = simulator.run(circuit, repetitions=100)

# Collect the measurement results
measurements = result.measurements
counts = Counter(tuple(measurements[f'result_{i}'][j][0] for i in range(2)) for j in range(100))

# Print the measurement results
print("Measurement results (bitstring: frequency):")
for outcome, frequency in counts.items():
    print(f"{outcome}: {frequency}")

# Print the circuit
print("\nCircuit:")
print(circuit)

Measurement results (bitstring: frequency):
(np.int8(0), np.int8(1)): 47
(np.int8(0), np.int8(0)): 53

Circuit:
          ┌                               ┐
          │1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0│
          │0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0│
          │0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0│
0: ───H───│0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0│───H───M('result_0')───
          │0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0│
          │0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0│
          │0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0│
          │0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0│
          │0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1│
          │0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0│
          │0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0│
          │0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0│
          └                               ┘
          │
1: ───H───#2──────────────────────────────────H───M('result_1